version: '3.4'

services:
  lenin:
    image: mongo:4.4.6
    restart: always
    ports:
      - 27017
    environment:
     MONGO_INITDB_ROOT_USERNAME: root
     MONGO_INITDB_ROOT_PASSWORD: Gam3rt3chPASSW0rD
    volumes:
      - ./data/db:/data/db
    networks:
      - bd

networks:
  bd:
    external: true